In [6]:
# Esto es un comentario

'''
Desarrollador: Amaru Fernandez
Ubicacion: santiago
Version python: 3.8
'''

nombre = "Amaru"
apellido = "Fernandez"
nombre_completo = nombre + " " + apellido
nombre_completo

'Amaru Fernandez'

In [62]:
import time

# Ejemplo 1: Iterando sobre una lista
numeros = [1, 22, 3, 4, 55, 6]
for numero in numeros:
    print(numero)

time.sleep(0.3)
ahora = time.ctime()

print(ahora)
print("fin")


1
22
3
4
55
6
Fri May 26 20:00:58 2023
fin


In [12]:
# Ejemplo 2: Iterando sobre una cadena de texto
mensaje = "Hola, mundo!"
for caracter in mensaje:
    print(caracter)

# Ejemplo 3: Iterando sobre un rango de números
for i in range(1, 6):
    print(i)

H
o
l
a
,
 
m
u
n
d
o
!
1
2
3
4
5


In [21]:
huevos = ['bueno', 'bueno', 'malo', 'bueno', 'bueno', 'bueno', "mas o menos"]
huevos_buenos = 0
huevos_malos = 0
huevos_otros = 0
for huevo in huevos:
    if huevo == 'malo':
        huevos_malos += 1
    elif huevo == 'bueno':
        huevos_buenos += 1
    else:
        huevos_otros += 1
    
    if huevo == 'malo' or huevo != 'bueno':
        print("Se cambia el huevo porque salio "+ huevo)


print("hay {} huevos buenos, {} huevos malos y {} huevos indefinidos".format(huevos_buenos,huevos_malos,huevos_otros))

## Otras formas de concatenar informacion
# print("hay " + str(huevos_buenos) + " huevos buenos y " + str(huevos_malos) + " huevos malos")
# print(f"hay {huevos_buenos} huevos buenos y {huevos_malos} huevos malos")
print(huevos)

Se cambia el huevo porque salio malo
Se cambia el huevo porque salio mas o menos
hay 5 huevos buenos, 1 huevos malos y 1 huevos indefinidos
['bueno', 'bueno', 'malo', 'bueno', 'bueno', 'bueno', 'mas o menos']


In [31]:
huevos = ['bueno', 'bueno', 'malo', 'bueno', 'bueno', 'bueno', "mas o menos"]
hist_huevos_cambiados = list()
huevos_buenos = 0
huevos_malos = 0
huevos_otros = 0
for posicion_huevo in range(0, len(huevos)):
    if huevos[posicion_huevo] == 'malo':
        huevos_malos += 1
    elif huevos[posicion_huevo] == 'bueno':
        huevos_buenos += 1
    else:
        huevos_otros += 1
    
    if huevos[posicion_huevo] == 'malo' or huevos[posicion_huevo] != 'bueno':
        print("Se cambia el huevo porque salio "+ huevos[posicion_huevo])
        huevos[posicion_huevo] = "bueno"
        hist_huevos_cambiados.append(posicion_huevo)


print("hay {} huevos buenos, {} huevos malos y {} huevos indefinidos".format(huevos_buenos,huevos_malos,huevos_otros))
print(f"se cambiaron los huevos: {hist_huevos_cambiados}")

## Otras formas de concatenar informacion
# print("hay " + str(huevos_buenos) + " huevos buenos y " + str(huevos_malos) + " huevos malos")
# print(f"hay {huevos_buenos} huevos buenos y {huevos_malos} huevos malos")
print(huevos)

Se cambia el huevo porque salio malo
Se cambia el huevo porque salio mas o menos
hay 5 huevos buenos, 1 huevos malos y 1 huevos indefinidos
se cambiaron los huevos: [2, 6]
['bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno']


In [6]:
import random

n = 10  # Longitud deseada de la lista
elementos = ["bueno", "malo", "mas o menos"]  # Elementos posibles

lista_aleatoria = [random.choice(elementos) for _ in range(n)]
print(lista_aleatoria)

['malo', 'malo', 'bueno', 'malo', 'bueno', 'malo', 'mas o menos', 'mas o menos', 'mas o menos', 'mas o menos']


In [21]:
lista_aleatoria[:]

['malo',
 'malo',
 'bueno',
 'malo',
 'bueno',
 'malo',
 'mas o menos',
 'mas o menos',
 'mas o menos',
 'mas o menos']

In [35]:
import random

n = 50  # Longitud deseada de la lista
elementos = ["bueno", "malo", "mas o menos"]  # Elementos posibles

huevos = [random.choice(elementos) for _ in range(n)]
hist_huevos_cambiados = list()
huevos_buenos = 0
huevos_malos = 0
huevos_otros = 0
for posicion_huevo in range(0, len(huevos)):
    if huevos[posicion_huevo] == 'malo':
        huevos_malos += 1
    elif huevos[posicion_huevo] == 'bueno':
        huevos_buenos += 1
    else:
        huevos_otros += 1
    
    if huevos[posicion_huevo] == 'malo' or huevos[posicion_huevo] != 'bueno':
        # print("Se cambia el huevo porque salio "+ huevos[posicion_huevo])
        huevos[posicion_huevo] = "bueno"
        hist_huevos_cambiados.append(posicion_huevo)


print("hay {} huevos buenos, {} huevos malos y {} huevos indefinidos".format(huevos_buenos,huevos_malos,huevos_otros))
print(f"se cambiaron los huevos: {hist_huevos_cambiados}")

print(huevos)

hay 16 huevos buenos, 12 huevos malos y 22 huevos indefinidos
se cambiaron los huevos: [0, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 14, 15, 18, 19, 20, 21, 22, 23, 25, 26, 28, 29, 32, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46]
['bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno', 'bueno']


In [31]:
# viendo diccionario
dict_comprador = dict()

# verificando el tipo de dato
print(type(dict_comprador))


dict_comprador['nom'] = "Antonia"
dict_comprador['ape_pat'] = "Fernándes"


print(dict_comprador)

print(dict_comprador['nom'])


<class 'dict'>
{'nom': 'Antonia', 'ape_pat': 'Fernándes'}
Antonia


In [26]:
import random

diccionario = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
claves = list(diccionario.keys())
random.shuffle(claves)

for clave in claves:
    valor = diccionario[clave]
    print(clave, valor)


b 2
d 4
c 3
a 1


In [42]:
mi_uf = {
  "version": "1.7.0",
  "autor": "mindicador.cl",
  "codigo": "uf",
  "nombre": "Unidad de fomento (UF)",
  "unidad_medida": "Pesos",
  "serie": [
    {
      "fecha": "2023-05-26T04:00:00.000Z",
      "valor": 36015.48
    },
    {
      "fecha": "2023-05-25T04:00:00.000Z",
      "valor": 36012
    }
  ]
}
print(type(mi_uf))

serie = mi_uf['serie']
print(type(serie))
print(type(serie[0]))
print(serie[0]['fecha'])


<class 'dict'>
<class 'list'>
<class 'dict'>
2023-05-26T04:00:00.000Z


In [35]:
mi_uf = {
  "version": "1.7.0",
  "autor": "mindicador.cl",
  "codigo": "uf",
  "nombre": "Unidad de fomento (UF)",
  "unidad_medida": "Pesos",
  "serie": { 
    0 : {
      "fecha": "2023-05-26T04:00:00.000Z",
      "valor": 36015.48
    },
    1 : {
      "fecha": "2023-05-25T04:00:00.000Z",
      "valor": 36012
    }
  }
}
print(type(mi_uf))

mi_uf['serie']

<class 'dict'>


{0: {'fecha': '2023-05-26T04:00:00.000Z', 'valor': 36015.48},
 1: {'fecha': '2023-05-25T04:00:00.000Z', 'valor': 36012}}

In [56]:
from datetime import datetime

texto_fecha = "2023-05-26T04:00:00.000Z"
fecha = datetime.strptime(texto_fecha, "%Y-%m-%dT%H:%M:%S.%fZ")

print(fecha)

2023-05-26 04:00:00


In [57]:
!#pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 12.2 MB/s eta 0:00:0000:0100:01
You should consider upgrading via the '/Users/amaru/.pyenv/versions/3.8.16/bin/python3.8 -m pip install --upgrade pip' command.


In [60]:
import numpy as np

In [79]:
arreglo_np = np.array([22,23,63,52,42])
arreglo_np = np.array([[22,23,63,52,42],[84,26,25,24,34]])
arreglo_np = np.array([
                       [[22,23,63,52,42],[84,26,25,24,34],[22,23,63,52,42]],
                       [[22,23,63,52,42],[84,26,25,24,34],[22,23,63,52,42]],
                       [[22,23,63,52,42],[84,26,25,24,34],[22,23,63,52,42]],
                       [[22,23,63,52,42],[84,26,25,24,34],[22,23,63,52,42]]
                       ])
print(arreglo_np[1,1,1])
print(arreglo_np.shape)

26
(4, 3, 5)


In [101]:
arreglo_np = arreglo_np.reshape(2, 2,-1)

In [102]:
arreglo_np.shape

(2, 2, 15)

In [113]:
arreglo_np % 2

array([[[11, 11, 31, 26, 21, 42, 13, 12, 12, 17, 11, 11, 31, 26, 21],
        [11, 11, 31, 26, 21, 42, 13, 12, 12, 17, 11, 11, 31, 26, 21]],

       [[11, 11, 31, 26, 21, 42, 13, 12, 12, 17, 11, 11, 31, 26, 21],
        [11, 11, 31, 26, 21, 42, 13, 12, 12, 17, 11, 11, 31, 26, 21]]])

In [104]:
for fila in arreglo_np:
    for elemento in fila:
        print(elemento)

[22 23 63 52 42 84 26 25 24 34 22 23 63 52 42]
[22 23 63 52 42 84 26 25 24 34 22 23 63 52 42]
[22 23 63 52 42 84 26 25 24 34 22 23 63 52 42]
[22 23 63 52 42 84 26 25 24 34 22 23 63 52 42]


In [ ]:
for elemento in np.nditer(arreglo_np):
    print(elemento)

In [ ]:
for elemento in arreglo_np.flat:
    print(elemento)

In [108]:
for columna in np.transpose(arreglo_np):
    for elemento in columna:
        print(elemento*2)

[44 44]
[44 44]
[46 46]
[46 46]
[126 126]
[126 126]
[104 104]
[104 104]
[84 84]
[84 84]
[168 168]
[168 168]
[52 52]
[52 52]
[50 50]
[50 50]
[48 48]
[48 48]
[68 68]
[68 68]
[44 44]
[44 44]
[46 46]
[46 46]
[126 126]
[126 126]
[104 104]
[104 104]
[84 84]
[84 84]
